"""
visualize_probe_data.py
=======================
Load and visualize probe time signals and correlations from HDF5 output.

This script reads the HDF5 file generated by probe_time_signals.py or 
probe_time_signals_2.py and creates comprehensive visualizations.

USAGE
-----
    python visualize_probe_data.py

Edit the INPUT_FILE path below to point to your HDF5 data file.
"""

import os
import h5py
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.gridspec import GridSpec

# ============================================================================
# CONFIGURATION
# ============================================================================

# Path to HDF5 file containing probe data
INPUT_FILE = (
    "/home/jofre/Members/Eduard/Paper2/Simulations/"
    "NACA_0012_AOA12_Re50000_1716x1662x128/Mean_data/"
    "Probe_time_signals/probe_time_signals_2.h5"
)

# Output directory for plots (optional - set to None to only show plots)
OUTPUT_DIR = None  # or specify a directory path to save figures

# Plot settings
FIGSIZE_LARGE = (14, 10)
FIGSIZE_MEDIUM = (12, 6)
FIGSIZE_SMALL = (10, 5)


# ============================================================================
# LOAD DATA
# ============================================================================

print("=" * 70)
print("PROBE DATA VISUALIZATION")
print("=" * 70)

print(f"\nLoading data from:\n  {INPUT_FILE}")

if not os.path.exists(INPUT_FILE):
    raise FileNotFoundError(f"File not found: {INPUT_FILE}")

# Read all data into memory
with h5py.File(INPUT_FILE, "r") as f:
    
    # Global metadata
    AOA_deg = f.attrs['AOA_deg']
    midplane_idx = f.attrs['midplane_idx']
    n_snapshots = f.attrs['n_snapshots']
    n_surf_probes = f.attrs['n_surf_probes']
    n_domain_probes = f.attrs['n_domain_probes']
    first_ts = f.attrs['first_timestamp']
    last_ts = f.attrs['last_timestamp']
    
    corr_method = f.attrs.get('correlation_method', 'FFT')
    
    print(f"\n  Dataset summary:")
    print(f"    AOA               : {AOA_deg}°")
    print(f"    Snapshots         : {n_snapshots}")
    print(f"    Surface probes    : {n_surf_probes}")
    print(f"    Domain probes     : {n_domain_probes}")
    print(f"    Correlation method: {corr_method}")
    print(f"    Timestamp range   : {first_ts} → {last_ts}")
    
    # Load surface probe data
    surf_probes = []
    for k in range(n_surf_probes):
        grp = f[f"time_series/surf_{k}"]
        surf_probes.append({
            'xc_target': grp.attrs['xc_target'],
            'xc_actual': grp.attrs['xc_actual'],
            'y_actual': grp.attrs['y_actual'],
            'global_idx': grp.attrs['global_idx'],
            'tau_w_mean': grp.attrs['tau_w_mean'],
            'tau_w_rms': grp.attrs['tau_w_rms'],
            'tau_prime': grp['tau_prime'][:]
        })
        print(f"\n  Surface probe {k}:")
        print(f"    x/c = {surf_probes[k]['xc_actual']:.4f} (target: {surf_probes[k]['xc_target']:.2f})")
        print(f"    τ_w,mean = {surf_probes[k]['tau_w_mean']:.4e}")
        print(f"    τ_w,rms  = {surf_probes[k]['tau_w_rms']:.4e}")
    
    # Load domain probe data
    domain_probes = []
    for j in range(n_domain_probes):
        grp = f[f"time_series/domain_{j}"]
        domain_probes.append({
            'x_target': grp.attrs['x_target'],
            'y_target': grp.attrs['y_target'],
            'x_actual': grp.attrs['x_actual'],
            'y_actual': grp.attrs['y_actual'],
            'iy': grp.attrs['iy'],
            'ix': grp.attrs['ix'],
            'u_mean': grp.attrs['u_mean'],
            'u_prime': grp['u_prime'][:]
        })
        print(f"\n  Domain probe {j}:")
        print(f"    (x, y) = ({domain_probes[j]['x_actual']:.4f}, {domain_probes[j]['y_actual']:.4f})")
        print(f"    u_mean = {domain_probes[j]['u_mean']:.4f}")
    
    # Load correlation data
    correlations = {}
    for k in range(n_surf_probes):
        for j in range(n_domain_probes):
            key = f"surf{k}_dom{j}"
            grp = f[f"correlations/{key}"]
            correlations[(k, j)] = {
                'R0': grp.attrs['R0'],
                'peak_lag': grp.attrs['peak_lag'],
                'peak_R': grp.attrs['peak_R'],
                'lags': grp['lags'][:],
                'R_tau': grp['R_tau'][:],
                'running_R0': grp['running_R0'][:]
            }
            print(f"\n  Correlation surf[{k}] × dom[{j}]:")
            print(f"    R(0)     = {correlations[(k, j)]['R0']:.4f}")
            print(f"    Peak R   = {correlations[(k, j)]['peak_R']:.4f} at lag = {correlations[(k, j)]['peak_lag']}")


print("\n" + "=" * 70)
print("GENERATING VISUALIZATIONS")
print("=" * 70)

snap_indices = np.arange(n_snapshots)


# ============================================================================
# PLOT 1: Time series overview for all probes
# ============================================================================
print("\n1. Time series overview...")

n_surf = len(surf_probes)
n_dom = len(domain_probes)

fig1 = plt.figure(figsize=(14, 3 * (n_surf + n_dom)))
gs = GridSpec(n_surf + n_dom, 1, figure=fig1, hspace=0.4)

# Surface probes
for k, probe in enumerate(surf_probes):
    ax = fig1.add_subplot(gs[k, 0])
    tau_norm = probe['tau_prime'] / probe['tau_w_rms']
    ax.plot(snap_indices, tau_norm, color='steelblue', lw=0.6, alpha=0.8)
    ax.axhline(0, color='k', lw=0.5, ls=':')
    ax.set_ylabel(r"$\tau'_w / \tau_{rms}$", fontsize=10)
    ax.set_title(f"Surface probe {k}: x/c = {probe['xc_actual']:.3f}", 
                 fontsize=11, fontweight='bold')
    ax.grid(True, alpha=0.3)
    if k < n_surf - 1:
        ax.set_xticklabels([])

# Domain probes
for j, probe in enumerate(domain_probes):
    ax = fig1.add_subplot(gs[n_surf + j, 0])
    u_rms = np.std(probe['u_prime'])
    u_norm = probe['u_prime'] / u_rms
    ax.plot(snap_indices, u_norm, color='tomato', lw=0.6, alpha=0.8)
    ax.axhline(0, color='k', lw=0.5, ls=':')
    ax.set_ylabel(r"$u' / \sigma_u$", fontsize=10)
    ax.set_title(f"Domain probe {j}: ({probe['x_actual']:.3f}, {probe['y_actual']:.3f})", 
                 fontsize=11, fontweight='bold')
    ax.grid(True, alpha=0.3)
    if j < n_dom - 1:
        ax.set_xticklabels([])

fig1.text(0.5, 0.02, 'Snapshot index', ha='center', fontsize=12)
fig1.suptitle('Time Series: All Probes (Normalized)', fontsize=14, fontweight='bold', y=0.995)
plt.tight_layout(rect=[0, 0.03, 1, 0.99])


# ============================================================================
# PLOT 2: Correlation functions for all probe pairs
# ============================================================================
print("2. Correlation functions...")

n_pairs = n_surf * n_dom
fig2 = plt.figure(figsize=(14, 4 * n_pairs))
gs2 = GridSpec(n_pairs, 1, figure=fig2, hspace=0.5)

pair_idx = 0
for k in range(n_surf):
    for j in range(n_dom):
        ax = fig2.add_subplot(gs2[pair_idx, 0])
        corr = correlations[(k, j)]
        
        ax.plot(corr['lags'], corr['R_tau'], color='navy', lw=1.5)
        ax.axvline(0, color='gray', ls=':', lw=1, alpha=0.7)
        ax.axhline(0, color='k', lw=0.5)
        
        # Mark peak
        ax.axvline(corr['peak_lag'], color='red', ls='--', lw=1.5, 
                   label=f"Peak: R={corr['peak_R']:.3f} at lag={corr['peak_lag']}")
        
        # Mark zero-lag
        ax.plot(0, corr['R0'], 'go', markersize=8, label=f"R(0)={corr['R0']:.3f}")
        
        ax.set_xlabel('Lag (snapshot index)', fontsize=10)
        ax.set_ylabel(r'$R(\tau)$', fontsize=11)
        ax.set_title(
            f"Surf[{k}] x/c={surf_probes[k]['xc_actual']:.3f}  ×  "
            f"Dom[{j}] ({domain_probes[j]['x_actual']:.3f}, {domain_probes[j]['y_actual']:.3f})",
            fontsize=11, fontweight='bold'
        )
        ax.legend(loc='best', fontsize=9)
        ax.grid(True, alpha=0.3)
        
        pair_idx += 1

fig2.suptitle('Cross-Correlation Functions: All Probe Pairs', fontsize=14, fontweight='bold', y=0.995)
plt.tight_layout(rect=[0, 0, 1, 0.99])


# ============================================================================
# PLOT 3: Running convergence (zero-lag correlation)
# ============================================================================
print("3. Convergence analysis...")

fig3 = plt.figure(figsize=(14, 4 * n_pairs))
gs3 = GridSpec(n_pairs, 1, figure=fig3, hspace=0.5)

pair_idx = 0
for k in range(n_surf):
    for j in range(n_dom):
        ax = fig3.add_subplot(gs3[pair_idx, 0])
        corr = correlations[(k, j)]
        
        ax.plot(snap_indices, corr['running_R0'], color='darkgreen', lw=1.2)
        ax.axhline(corr['R0'], color='red', ls='--', lw=1.5, 
                   label=f"Final R(0)={corr['R0']:.4f}")
        
        ax.set_xlabel('Number of snapshots', fontsize=10)
        ax.set_ylabel(r'Running $R(0)$', fontsize=11)
        ax.set_title(
            f"Convergence: Surf[{k}] × Dom[{j}]",
            fontsize=11, fontweight='bold'
        )
        ax.legend(loc='best', fontsize=9)
        ax.grid(True, alpha=0.3)
        
        pair_idx += 1

fig3.suptitle('Zero-Lag Correlation Convergence', fontsize=14, fontweight='bold', y=0.995)
plt.tight_layout(rect=[0, 0, 1, 0.99])


# ============================================================================
# PLOT 4: Correlation matrix (heatmap of R(0) values)
# ============================================================================
if n_surf > 1 and n_dom > 1:
    print("4. Correlation matrix...")
    
    R0_matrix = np.zeros((n_surf, n_dom))
    for k in range(n_surf):
        for j in range(n_dom):
            R0_matrix[k, j] = correlations[(k, j)]['R0']
    
    fig4, ax4 = plt.subplots(figsize=(8, 6))
    im = ax4.imshow(R0_matrix, cmap='RdBu_r', aspect='auto', vmin=-1, vmax=1)
    
    ax4.set_xticks(np.arange(n_dom))
    ax4.set_yticks(np.arange(n_surf))
    ax4.set_xticklabels([f"Dom {j}\n({domain_probes[j]['x_actual']:.2f}, "
                         f"{domain_probes[j]['y_actual']:.2f})" 
                         for j in range(n_dom)], fontsize=9)
    ax4.set_yticklabels([f"Surf {k}\nx/c={surf_probes[k]['xc_actual']:.2f}" 
                         for k in range(n_surf)], fontsize=9)
    
    # Add text annotations
    for k in range(n_surf):
        for j in range(n_dom):
            text = ax4.text(j, k, f"{R0_matrix[k, j]:.3f}",
                           ha="center", va="center", color="black", fontsize=10, 
                           fontweight='bold')
    
    cbar = plt.colorbar(im, ax=ax4)
    cbar.set_label(r'$R(0)$', fontsize=12)
    ax4.set_title('Zero-Lag Correlation Matrix', fontsize=13, fontweight='bold')
    plt.tight_layout()


# ============================================================================
# PLOT 5: Selected probe pair - detailed view
# ============================================================================
print("5. Detailed view of probe pair [0, 0]...")

k0, j0 = 0, 0
probe_surf = surf_probes[k0]
probe_dom = domain_probes[j0]
corr = correlations[(k0, j0)]

fig5 = plt.figure(figsize=(14, 10))
gs5 = GridSpec(3, 2, figure=fig5, hspace=0.35, wspace=0.3)

# Top left: tau' time series
ax1 = fig5.add_subplot(gs5[0, 0])
tau_norm = probe_surf['tau_prime'] / probe_surf['tau_w_rms']
ax1.plot(snap_indices, tau_norm, color='steelblue', lw=0.7)
ax1.axhline(0, color='k', lw=0.5, ls=':')
ax1.set_ylabel(r"$\tau'_w / \tau_{rms}$", fontsize=11)
ax1.set_title(f"Surface: x/c = {probe_surf['xc_actual']:.3f}", fontsize=11, fontweight='bold')
ax1.grid(True, alpha=0.3)

# Top right: u' time series
ax2 = fig5.add_subplot(gs5[0, 1])
u_rms = np.std(probe_dom['u_prime'])
u_norm = probe_dom['u_prime'] / u_rms
ax2.plot(snap_indices, u_norm, color='tomato', lw=0.7)
ax2.axhline(0, color='k', lw=0.5, ls=':')
ax2.set_ylabel(r"$u' / \sigma_u$", fontsize=11)
ax2.set_title(f"Domain: ({probe_dom['x_actual']:.3f}, {probe_dom['y_actual']:.3f})", 
              fontsize=11, fontweight='bold')
ax2.grid(True, alpha=0.3)

# Middle: overlaid time series
ax3 = fig5.add_subplot(gs5[1, :])
ax3_twin = ax3.twinx()
line1 = ax3.plot(snap_indices, tau_norm, color='steelblue', lw=0.8, 
                 label=r"$\tau'_w / \tau_{rms}$", alpha=0.8)
line2 = ax3_twin.plot(snap_indices, u_norm, color='tomato', lw=0.8, 
                      label=r"$u' / \sigma_u$", alpha=0.8)
ax3.axhline(0, color='k', lw=0.5, ls=':')
ax3_twin.axhline(0, color='k', lw=0.5, ls=':', alpha=0.5)
ax3.set_xlabel('Snapshot index', fontsize=11)
ax3.set_ylabel(r"$\tau'_w / \tau_{rms}$", color='steelblue', fontsize=11)
ax3_twin.set_ylabel(r"$u' / \sigma_u$", color='tomato', fontsize=11)
ax3.set_title('Overlaid Time Series', fontsize=11, fontweight='bold')

lines = line1 + line2
labels = [l.get_label() for l in lines]
ax3.legend(lines, labels, loc='upper right', fontsize=10)
ax3.grid(True, alpha=0.3)

# Bottom left: correlation function
ax4 = fig5.add_subplot(gs5[2, 0])
ax4.plot(corr['lags'], corr['R_tau'], color='navy', lw=1.5)
ax4.axvline(0, color='gray', ls=':', lw=1, alpha=0.7)
ax4.axhline(0, color='k', lw=0.5)
ax4.axvline(corr['peak_lag'], color='red', ls='--', lw=1.5, 
            label=f"Peak: R={corr['peak_R']:.3f} at lag={corr['peak_lag']}")
ax4.plot(0, corr['R0'], 'go', markersize=10, label=f"R(0)={corr['R0']:.3f}", zorder=5)
ax4.set_xlabel('Lag (snapshot index)', fontsize=11)
ax4.set_ylabel(r'$R(\tau)$', fontsize=11)
ax4.set_title('Cross-Correlation', fontsize=11, fontweight='bold')
ax4.legend(loc='best', fontsize=9)
ax4.grid(True, alpha=0.3)

# Bottom right: convergence
ax5 = fig5.add_subplot(gs5[2, 1])
ax5.plot(snap_indices, corr['running_R0'], color='darkgreen', lw=1.5)
ax5.axhline(corr['R0'], color='red', ls='--', lw=1.5, 
            label=f"Final R(0)={corr['R0']:.4f}")
ax5.set_xlabel('Number of snapshots', fontsize=11)
ax5.set_ylabel(r'Running $R(0)$', fontsize=11)
ax5.set_title('Convergence Check', fontsize=11, fontweight='bold')
ax5.legend(loc='best', fontsize=9)
ax5.grid(True, alpha=0.3)

fig5.suptitle(f'Detailed Analysis: Surf[{k0}] × Dom[{j0}]', 
              fontsize=14, fontweight='bold', y=0.995)
plt.tight_layout(rect=[0, 0, 1, 0.99])


# ============================================================================
# PLOT 6: PDF/histogram of fluctuations
# ============================================================================
print("6. Probability distributions...")

fig6 = plt.figure(figsize=(14, 5))
gs6 = GridSpec(1, 2, figure=fig6, wspace=0.3)

# Surface probe PDFs
ax1 = fig6.add_subplot(gs6[0, 0])
for k, probe in enumerate(surf_probes):
    tau_norm = probe['tau_prime'] / probe['tau_w_rms']
    ax1.hist(tau_norm, bins=50, alpha=0.6, density=True, 
             label=f"Surf {k}: x/c={probe['xc_actual']:.3f}")
ax1.axvline(0, color='k', lw=1, ls='--')
ax1.set_xlabel(r"$\tau'_w / \tau_{rms}$", fontsize=11)
ax1.set_ylabel('PDF', fontsize=11)
ax1.set_title('Surface Probes: Fluctuation Distribution', fontsize=11, fontweight='bold')
ax1.legend(fontsize=9)
ax1.grid(True, alpha=0.3, axis='y')

# Domain probe PDFs
ax2 = fig6.add_subplot(gs6[0, 1])
for j, probe in enumerate(domain_probes):
    u_rms = np.std(probe['u_prime'])
    u_norm = probe['u_prime'] / u_rms
    ax2.hist(u_norm, bins=50, alpha=0.5, density=True, 
             label=f"Dom {j}: ({probe['x_actual']:.2f}, {probe['y_actual']:.2f})")
ax2.axvline(0, color='k', lw=1, ls='--')
ax2.set_xlabel(r"$u' / \sigma_u$", fontsize=11)
ax2.set_ylabel('PDF', fontsize=11)
ax2.set_title('Domain Probes: Fluctuation Distribution', fontsize=11, fontweight='bold')
ax2.legend(fontsize=8, loc='upper right')
ax2.grid(True, alpha=0.3, axis='y')

fig6.suptitle('Probability Density Functions', fontsize=13, fontweight='bold', y=0.98)
plt.tight_layout(rect=[0, 0, 1, 0.96])


# ============================================================================
# SAVE OR SHOW
# ============================================================================
print("\n" + "=" * 70)
print("DISPLAY/SAVE")
print("=" * 70)

if OUTPUT_DIR is not None:
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    
    fig1.savefig(os.path.join(OUTPUT_DIR, "01_time_series_all.png"), dpi=150, bbox_inches='tight')
    print(f"  Saved: 01_time_series_all.png")
    
    fig2.savefig(os.path.join(OUTPUT_DIR, "02_correlations_all.png"), dpi=150, bbox_inches='tight')
    print(f"  Saved: 02_correlations_all.png")
    
    fig3.savefig(os.path.join(OUTPUT_DIR, "03_convergence_all.png"), dpi=150, bbox_inches='tight')
    print(f"  Saved: 03_convergence_all.png")
    
    if n_surf > 1 and n_dom > 1:
        fig4.savefig(os.path.join(OUTPUT_DIR, "04_correlation_matrix.png"), dpi=150, bbox_inches='tight')
        print(f"  Saved: 04_correlation_matrix.png")
    
    fig5.savefig(os.path.join(OUTPUT_DIR, "05_detailed_pair00.png"), dpi=150, bbox_inches='tight')
    print(f"  Saved: 05_detailed_pair00.png")
    
    fig6.savefig(os.path.join(OUTPUT_DIR, "06_PDFs.png"), dpi=150, bbox_inches='tight')
    print(f"  Saved: 06_PDFs.png")
    
    print(f"\n  All plots saved to: {OUTPUT_DIR}")

print("\n  Displaying plots...")
plt.show()

print("\n" + "=" * 70)
print("DONE")
print("=" * 70)
